name: FlightCompensation
options:
  bundleIdPrefix: com.flightcompensation
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

targets:
  FlightCompensation:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: FlightCompensation
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.flightcompensation.app
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "-"
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG $(inherited)"
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        INFOPLIST_FILE: Info.plist
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: "YES"
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: "YES"
        INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG $(inherited)"
        Release:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: ""

